### ISSUE TITLE
Error play from A-Z listing

### ISSUE THREAD

**Issue by mrRobit** [kodi-czsk/plugin.video.rtvs.sk#16]
Pri spustani konkretnej relacie zo zoznamu vylistovaneho podla pismena sa spustenie nepodari. Chyba z logu vid nizsie.
_Pozn: Pri spustani podla datumu vysielania prehravanie funguje korektne_

`2020-02-15 23:54:37.697 T:1533780864  NOTICE: ['[rtvs.sk] AZ listing: ?l=t&ord=az']
2020-02-15 23:54:56.145 T:1402991488  NOTICE: ["Initializing provider rtvs.sk with settings {'lang': '0', 'downloads': '', 'quality': '0'}"]
2020-02-15 23:54:56.145 T:1402991488  NOTICE: ['[rtvs.sk] EPISODE listing: /televizia/archiv/15363/213801']
2020-02-15 23:54:56.654 T:1402991488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.rtvs.sk/default.py", line 111, in <module>
                                                RtvsXBMCContentProvider(rtvs.RtvsContentProvider(tmp_dir=xbmc.translatePath(__addon__.getAddonInfo('profile'))
), settings, __addon__).run(params)
                                              File "/storage/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 82, in run
                                                self.list(self.provider.list(params['list']))
                                              File "/storage/.kodi/addons/plugin.video.rtvs.sk/resources/lib/rtvs.py", line 149, in list
                                                return self.list_episodes(util.request(self._fix_url(url)))
                                              File "/storage/.kodi/addons/plugin.video.rtvs.sk/resources/lib/rtvs.py", line 260, in list_episodes
                                                current_date = to_unicode(re.search(LISTING_DATE_RE, page, re.IGNORECASE | re.DOTALL).group('date'))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2020-02-15 23:54:56.828 T:1533780864   ERROR: GetDirectory - Error getting plugin://plugin.video.rtvs.sk/?cp=727476732e736b&list=2f74656c6576697a69612f6172636
869762f31353336332f323133383031
2020-02-15 23:54:56.830 T:1936825776   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rtvs.sk/?cp=727476732e736b&list=2f74656c6576697a69612f617263
6869762f31353336332f323133383031) failed`

**Comment by rywko** [comment]
Chyba je opravena v #15 
Ak chces dostavat aktualizacie doplnkov skor, odporucam pouzit novy repozitar:
`https://www.xbmc-kodi.cz/repo.php`
