### ISSUE TITLE
Livestream not working on 18.2-RC2

### ISSUE THREAD

**Issue by matejmosko** [kodi-czsk/plugin.video.rtvs.sk#9]
After update to 1.8.0 the livestream doesn't work on kodi 18.2-RC2 because the addon checks for the version of kodi as float. However "18.2-RC2" isn't float and cannot be compared to >=18.

Log here: https://paste.kodi.tv/covomupune

Problem clearly seen here:

```````
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for float(): 18.2-RC1
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.rtvs.sk/default.py", line 111, in <module>
                                                RtvsXBMCContentProvider(rtvs.RtvsContentProvider(tmp_dir=xbmc.translatePath(__addon__.getAddonInfo('profile'))), settings, __addon__).run(params)
                                              File "/home/osmc/.kodi/addons/script.module.stream.resolver/lib/contentprovider/xbmcprovider.py", line 87, in run
                                                return self.play({'url': params['play'], 'info': params})
                                              File "/home/osmc/.kodi/addons/plugin.video.rtvs.sk/default.py", line 41, in play
                                                stream = self.resolve(item['url'])
                                              File "/home/osmc/.kodi/addons/plugin.video.rtvs.sk/default.py", line 104, in resolve
                                                return self.provider.resolve(item, select_cb=select_cb)
                                              File "/home/osmc/.kodi/addons/plugin.video.rtvs.sk/resources/lib/rtvs.py", line 301, in resolve
                                                if is_kodi_leia():
                                              File "/home/osmc/.kodi/addons/plugin.video.rtvs.sk/resources/lib/rtvs.py", line 92, in is_kodi_leia
                                                if (float(version) >= 18):
                                            ValueError: invalid literal for float(): 18.2-RC1
                                            -->End of Python script error report<--
````````

**Comment by matejmosko** [comment]
Fix already in code. Version bump initiated for the change to be included https://github.com/kodi-czsk/plugin.video.rtvs.sk/pull/11
